//
//  DicomConstants.h
//  RMi
//
//  Created by Marcelo da Mata on 26/03/2013.
//
//

#import <Foundation/Foundation.h>

@interface DicomConstants : NSObject

FOUNDATION_EXPORT int const PIXEL_REPRESENTATION;
FOUNDATION_EXPORT int const TRANSFER_SYNTAX_UID;
FOUNDATION_EXPORT int const MODALITY;
FOUNDATION_EXPORT int const SLICE_THICKNESS;
FOUNDATION_EXPORT int const SLICE_SPACING;
FOUNDATION_EXPORT int const IMAGER_PIXEL_SPACING;
FOUNDATION_EXPORT int const SAMPLES_PER_PIXEL;
FOUNDATION_EXPORT int const PHOTOMETRIC_INTERPRETATION;
FOUNDATION_EXPORT int const PLANAR_CONFIGURATION;
FOUNDATION_EXPORT int const NUMBER_OF_FRAMES;
FOUNDATION_EXPORT int const ROWS;
FOUNDATION_EXPORT int const COLUMNS;
FOUNDATION_EXPORT int const PIXEL_SPACING;
FOUNDATION_EXPORT int const BITS_ALLOCATED;
FOUNDATION_EXPORT int const WINDOW_CENTER;
FOUNDATION_EXPORT int const WINDOW_WIDTH;
FOUNDATION_EXPORT int const RESCALE_INTERCEPT;
FOUNDATION_EXPORT int const RESCALE_SLOPE;
FOUNDATION_EXPORT int const RED_PALETTE;
FOUNDATION_EXPORT int const GREEN_PALETTE;
FOUNDATION_EXPORT int const BLUE_PALETTE;
FOUNDATION_EXPORT int const ICON_IMAGE_SEQUENCE;
FOUNDATION_EXPORT int const ITEM;
FOUNDATION_EXPORT int const ITEM_DELEMITATION;
FOUNDATION_EXPORT int const SEQUENCE_DELEMITATION;
FOUNDATION_EXPORT int const PIXEL_DATA;
FOUNDATION_EXPORT int const DEPTH;

FOUNDATION_EXPORT int const ICON_IMAGE_SEQUENCE;

FOUNDATION_EXPORT char const hexDigits[];

FOUNDATION_EXPORT int const IMPLICIT_VR;

FOUNDATION_EXPORT int const ID_OFFSET;
FOUNDATION_EXPORT NSString *const DICM;

FOUNDATION_EXPORT int const AE;
FOUNDATION_EXPORT int const AS;
FOUNDATION_EXPORT int const AT;
FOUNDATION_EXPORT int const CS;
FOUNDATION_EXPORT int const DA;
FOUNDATION_EXPORT int const DS;
FOUNDATION_EXPORT int const DT;
FOUNDATION_EXPORT int const FD;
FOUNDATION_EXPORT int const FL;
FOUNDATION_EXPORT int const IS;
FOUNDATION_EXPORT int const LO;
FOUNDATION_EXPORT int const LT;
FOUNDATION_EXPORT int const PN;
FOUNDATION_EXPORT int const SH;
FOUNDATION_EXPORT int const SL;
FOUNDATION_EXPORT int const SS;
FOUNDATION_EXPORT int const ST;
FOUNDATION_EXPORT int const TM;
FOUNDATION_EXPORT int const UI;
FOUNDATION_EXPORT int const UL;
FOUNDATION_EXPORT int const US;
FOUNDATION_EXPORT int const UT;
FOUNDATION_EXPORT int const OB;
FOUNDATION_EXPORT int const OW;
FOUNDATION_EXPORT int const SQ;
FOUNDATION_EXPORT int const UN;
FOUNDATION_EXPORT int const QQ;


/** Inteiro 8-bit sem sinal (0-255). */
FOUNDATION_EXPORT int const GRAY8;

/** Inteiro 16-bit com sinal (-32628-32627). */
FOUNDATION_EXPORT int const GRAY16_SIGNED;

/** Inteiro 16-bit sem sinal(0-65535)  */
FOUNDATION_EXPORT int const GRAY16_UNSIGNED;

/** Inteiro 32-bit sem sinal. Inteiro de 32-bit de imagens s'ao convertidos para floating*/
FOUNDATION_EXPORT int const GRAY32_UNSIGNED;

FOUNDATION_EXPORT int const GRAY32_INT;

FOUNDATION_EXPORT int const COLORB;

FOUNDATION_EXPORT int const RGB;

FOUNDATION_EXPORT int const RGB_PLANAR;
FOUNDATION_EXPORT int const BITMAP;


/** Compression modes */
FOUNDATION_EXPORT int const COMPRESSION_UNKNOWN;
FOUNDATION_EXPORT int const COMPRESSION_NONE;
FOUNDATION_EXPORT int const LZW;
FOUNDATION_EXPORT int const LZW_WITH_DIFFERENCING;
FOUNDATION_EXPORT int const JPEG;
FOUNDATION_EXPORT int const PACK_BITS;
FOUNDATION_EXPORT int const ZIP;

FOUNDATION_EXPORT int const DICOM_SIZE_HEAD;


@end
